### ISSUE TITLE
Can't use for Floor Projection.

### ISSUE THREAD

**Issue by TsubokuLab** [deprecatedcoder/PictureWindow#2]
Thank you for great asset.
but, I have one problem.
When I tried this asset as normally, It was success.
// The Blue rectangle is gizmos for _corners[]
![success](https://cloud.githubusercontent.com/assets/1589819/24364915/2d7b602e-134f-11e7-8c7a-031f9b7ac02c.png)
but, When I tried it for floor projection, it was failed.
![failure](https://cloud.githubusercontent.com/assets/1589819/24364918/3155aff6-134f-11e7-96b0-dfb7b5dd9709.png)

Do you have any ideas?

**Comment by deprecatedcoder** [comment]
First off, thanks for trying it out!

I think there were some assumptions made during development that have come to light now that people are trying it out.  This seems to be an example of that.  I wasn't really anticipating anyone with a display on the floor I guess.

I am not quite sure what the cause is, but I have some ideas.  I'll look into this the next time I am working on the project and will let you know what I find.

**Comment by TsubokuLab** [comment]
Thanks for early reply.
I'm looking forward it!

**Comment by deprecatedcoder** [comment]
Just to let you know, I fixed this in the most recent release for the standard view.  The enhanced view I also added still has a bug so doesn't work while on the floor just yet (and sorry for the slow response).
